### ISSUE TITLE
Formatting Rules & Organize Imports

### ISSUE THREAD

**Issue by michael-schnell** [smallrye/smallrye-code-rules#2]
- provide Eclipse formatting rules (could be used also in IntelliJ IDEA and Netbeans with a plugin)
- provide suggestions for Eclipse/IntelliJ IDEA/Netbeans on how to configure “Organize Imports”,

**Comment by michael-schnell** [comment]
See commit #1

**Comment by kenfinnigan** [comment]
Merged
